In [1]:
# Define a dictionary to store word embeddings
word_embedding = {
    # Each word is associated with a list of 3 numbers (its embedding)
    "cat": [0.2, 0.5, -0.1],
    "dog": [0.1, 0.4, 0.2],
    "fish": [-0.3, 0.1, 0.7]
}

# Retrieve the embedding for the word "cat"
cat_vector = word_embedding["dog"]

# Print the embedding for "cat"
print(cat_vector)  # This will output: [0.2, 0.5, -0.1]

[0.1, 0.4, 0.2]


In [2]:
import numpy as np

def simple_rotary_embedding(x, position):

    """
    x: original embedding vector
    position: position of the token in the sequence
    """

    # get the length of the input vector
    dim = len(x)

    # calculate the rotation angle based on the position
    theta = 0.1 * position
    print("Theta: ", theta)

    # create a new array of zeros with the same shape as x
    rotated_x = np.zeros_like(x)

    print("Rotated X: ", rotated_x)

    # Loop through the vector, taking 2 dimensions at a time
    for i in range(0, dim, 2):
        # Apply 2D rotation to each pair of dimensions
        rotated_x[i] = x[i] * np.cos(theta) - x[i+1] * np.sin(theta)
        rotated_x[i+1] = x[i] * np.sin(theta) + x[i+1] * np.cos(theta)

    return rotated_x


original_embedding = np.array([1, 2, 4, 1])

In [3]:
position_0 = simple_rotary_embedding(original_embedding, 0)
position_0

Theta:  0.0
Rotated X:  [0 0 0 0]


array([1, 2, 4, 1])

In [4]:
position_1 = simple_rotary_embedding(original_embedding, 1)
position_1

Theta:  0.1
Rotated X:  [0 0 0 0]


array([0, 2, 3, 1])

In [5]:
position_2 = simple_rotary_embedding(original_embedding, 2)
position_2

Theta:  0.2
Rotated X:  [0 0 0 0]


array([0, 2, 3, 1])